activity/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import (
    home, 
    JoinActivity, 
    CreateActivity, 
    ProfileHost, 
    ProfileJoin, 
    Moreinfo, 
    updateActivity, 
    deleteActivity, 
    leaveActivity,
    loginPage,
    register,
    logoutUser,
    updateUser,
    deleteUser
)
app_name = "activity"

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('register/', register, name='register'),

    path('updateUser/<id>', updateUser, name='updateuser'),
    path('deleteUser/<id>', deleteUser, name='deleteuser'),

    path('', home, name='home'),
    path('join/', JoinActivity, name='join'),
    path('create/', CreateActivity, name='create'),
    path('dashboard/', ProfileHost, name='profile-host'),
    path('dashboard1/', ProfileJoin, name='profile-join'),
    path('more-info/<id>', Moreinfo, name='more-info'),
    path('update/<id>', updateActivity, name='update'),
    path('delete/<id>', deleteActivity, name='delete'),
    path('deleteActivity', leaveActivity, name='leave'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                        document_root=settings.MEDIA_ROOT)

softwareeng/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("activity.urls", namespace="activity"))
]

activity/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    USER_TYPE = [
        ('admin', 'admin'),
        ('official', 'official'),
        ('normal', 'normal')
    ]
    profileImage = models.ImageField(upload_to='images/', null=True, blank=True)
    userType = models.CharField(max_length=10, choices=USER_TYPE, default='normal')
    userBio = models.CharField(max_length=100)

    def __str__(self):
        return self.username

class Activity(models.Model):
    activityOrganizer = models.ForeignKey(User, on_delete=models.CASCADE)
    activityTitle = models.CharField(max_length=50)
    activityLocation = models.CharField(max_length=100)
    activityDiscription = models.TextField()
    activityDate = models.DateTimeField()
    activityOpenDate = models.DateTimeField()
    activityCloseDate = models.DateTimeField()

    def __str__(self):
        return f"{self.activityTitle} organized by {self.activityOrganizer}"

class ActivityParticepationList(models.Model):
    class Meta:
        unique_together = (('userID', 'activityID'),)

    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    activityID = models.ForeignKey(Activity, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.userID} join {self.activityID}"

activity/forms.py
from django import forms
from .models import ActivityParticepationList
from .models import Activity
from .models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

class JoinActivityForm(forms.ModelForm):
    class Meta:
        model = ActivityParticepationList
        fields = (
            'userID',
            'activityID'
        )

class CreateActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = (
            '__all__'
        )

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username", 
            "first_name", 
            "last_name", 
            "password1", 
            "password2", 
            "userBio", 
            "profileImage"
        ]

class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username", 
            "first_name", 
            "last_name",
            "userBio",
            "profileImage"
        ]

activity/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Activity, ActivityParticepationList, User
from .forms import JoinActivityForm, CreateActivityForm, CreateUserForm, UpdateUserForm
from django.http import JsonResponse

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('activity:home')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('activity:home')
            else:
                messages.info(request, "username or password is wrong")
                
        context = {

        }
        return render(request, 'activity/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('activity:login')

def register(request):
    if request.user.is_authenticated:
        return redirect('activity:home')
    else:
        form = CreateUserForm()
        print(form)
        if request.method == "POST":
            form = CreateUserForm(request.POST, files=request.FILES)
            
            print(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "account created")
                return redirect('activity:login')

        context = {
            "form" : form
        }
        return render(request, 'activity/registration.html', context)

@login_required(login_url='activity:login')
def home(request):

    allActivities = Activity.objects.all().count()

    activities = []
    pagenation = [0,1,2,3,4]
    parList = []

    for activity in Activity.objects.all().order_by('-activityOpenDate'):
        particepance = ActivityParticepationList.objects.filter(activityID = activity.id) if ActivityParticepationList.objects.filter(activityID = activity.id).count() < 6 else ActivityParticepationList.objects.filter(activityID = activity.id)[:5]
        particepanceList = []
        for i in particepance:
            particepanceList.append(i.userID.id)
        lastestParticepance = ActivityParticepationList.objects.filter(activityID = activity.id).count()
        activityInfo = {"activity" : activity, "particepance" : particepance, "lastestParticepance" : lastestParticepance, "particepanceList" : particepanceList}
        # if activity.activityOrganizer.id != request.user.id:
        activities.append(activityInfo)

    

    context = {
        "activities" : activities,
        "allActivities" : allActivities,
        "pagenation" : pagenation,
        "parList" : parList
    }
    return render(request,'activity/home.html',context)

@login_required(login_url='activity:login')
def JoinActivity(request):
    form = JoinActivityForm()
    if request.method == "POST":
        print('Receiving a post request')
        print(request.POST)
        form = JoinActivityForm(request.POST)
        
        if form.is_valid():
            form.save()
    return HttpResponse(request.POST["activityID"])

@login_required(login_url='activity:login')
def CreateActivity(request):
    form = CreateActivityForm()
    if request.method == "POST":
        activity = form.save(commit=False)

        activity.activityOrganizer = request.user
        activity.activityTitle = request.POST["activityTitle"]
        activity.activityLocation = request.POST["activityLocation"]
        activity.activityDiscription = request.POST["activityDiscription"]
        activity.activityDate = request.POST["activityDate"]
        activity.activityOpenDate = request.POST["activityOpenDate"]
        activity.activityCloseDate = request.POST["activityCloseDate"]



        activity.save()
        return redirect("activity:profile-host")
        
    context = {
        "form" : CreateActivityForm()
    }
    return render(request, "activity/create.html", context)

@login_required(login_url='activity:login')
def ProfileHost(request):
    activities = []
    pagenation = [0,1,2,3,4]
    hostCount = Activity.objects.filter(activityOrganizer = request.user.id).count()
    joinCount = ActivityParticepationList.objects.filter(userID = request.user.id).count()

    for activity in Activity.objects.filter(activityOrganizer = request.user.id).order_by('-activityOpenDate'):
        particepance = ActivityParticepationList.objects.filter(activityID = activity.id) if ActivityParticepationList.objects.filter(activityID = activity.id).count() < 6 else ActivityParticepationList.objects.filter(activityID = activity.id)[:5]
        lastestParticepance = ActivityParticepationList.objects.filter(activityID = activity.id).count()
        activityInfo = {"activity" : activity, "particepance" : particepance, "lastestParticepance" : lastestParticepance}
        activities.append(activityInfo)


    context = {
        "activities" : activities,
        "pagenation" : pagenation,
        "hostCount" : hostCount,
        "joinCount" : joinCount

    }

    return render(request, "activity/profile-host.html", context)

@login_required(login_url='activity:login')
def ProfileJoin(request):
    activities = []
    pagenation = [0,1,2,3,4]

    hostCount = Activity.objects.filter(activityOrganizer = request.user.id).count()
    joinCount = ActivityParticepationList.objects.filter(userID = request.user.id).count()

    join = ActivityParticepationList.objects.filter(userID = request.user.id)
    joinList = []

    for i in join:
        joinList.append(i.activityID)
    for activity in joinList:
        particepance = ActivityParticepationList.objects.filter(activityID = activity.id) if ActivityParticepationList.objects.filter(activityID = activity.id).count() < 6 else ActivityParticepationList.objects.filter(activityID = activity.id)[:5]
        lastestParticepance = ActivityParticepationList.objects.filter(activityID = activity.id).count()
        # particepanceList = []
        # for i in particepance:
        #     particepanceList.append(i.userID.id)
        activityInfo = {"activity" : activity, "particepance" : particepance, "lastestParticepance" : lastestParticepance}
        activities.append(activityInfo)
    

    context = {
        "activities" : activities,
        "pagenation" : pagenation,
        "hostCount" : hostCount,
        "joinCount" : joinCount
        # "par" : par
    }

    return render(request, "activity/profile-join.html", context)

@login_required(login_url='activity:login')
def Moreinfo(request, id):
    activity = Activity.objects.get(id=id)
    parList = ActivityParticepationList.objects.filter(activityID = id)

    listPar = []

    for i in parList:
        # print(i.userID.id)
        listPar.append(i.userID.id)

    context = {
        "activity" : activity,
        "parList" : parList,
        "listPar" : listPar
    }

    return render(request, "activity/more_info.html", context)

@login_required(login_url='activity:login')
def updateActivity(request, id):
    activity = Activity.objects.get(id=id)
    form = CreateActivityForm(instance=activity)

    old = {
        "activityOrganizer" : activity.activityOrganizer,
        "activityTitle" : activity.activityTitle,
        "activityLocation" : activity.activityLocation,
        "activityDiscription" : activity.activityDiscription,

        "activityDate" : activity.activityDate.isoformat(),

        "activityOpenDate" : activity.activityOpenDate.isoformat(),
        "activityCloseDate" : activity.activityCloseDate.isoformat(),
    }


    if request.method == "POST":
        activity = form.save(commit=False)

        activity.activityOrganizer = request.user
        activity.activityTitle = request.POST["activityTitle"]
        activity.activityLocation = request.POST["activityLocation"]
        activity.activityDiscription = request.POST["activityDiscription"]
        activity.activityDate = request.POST["activityDate"]
        activity.activityOpenDate = request.POST["activityOpenDate"]
        activity.activityCloseDate = request.POST["activityCloseDate"]

        activity.save()
        return redirect("activity:profile-host")

    context = {
        "form" : form,
        "old" : old
    }

    return render(request, "activity/update.html", context)

@login_required(login_url='activity:login')
def updateUser(request, id):
    user = User.objects.get(id=id)
    form = UpdateUserForm(instance=user)
    

    if request.method == "POST":
        form = UpdateUserForm(request.POST, instance=user, files=request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect("activity:profile-host")

    context = {
        "form" : form,
    }

    return render(request, "activity/updateUser.html", context)


@login_required(login_url='activity:login')
def deleteActivity(request, id):
    activity = Activity.objects.get(id=id)
    activity.delete()
    return redirect("activity:profile-host")

@login_required(login_url='activity:login')
def deleteUser(request, id):
    user = User.objects.get(id=id)
    user.delete()
    messages.success(request, "The account has been deleted, Sad! anyway...")
    return redirect("activity:login")

@login_required(login_url='activity:login')
def leaveActivity(request):
    leaveItem = ActivityParticepationList.objects.filter(userID = request.user.id, activityID=request.POST["activityID"])
    leaveItem.delete()
    return HttpResponse("JOB DONE")

activity/templates/activity/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'activity/css/nav.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="//js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
    <script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
    <style>
        #logout-butt {
            padding: 1rem 2rem;
            width: 200px;
            background-color: #111;
            position: absolute;
            right: 250px;
            margin-top: 0.5rem;
            text-align: center;
            border-radius: 10px;
            display: none;
            transition: all 300ms ease-in;
        }

        #logout-butt a {
            text-decoration: none;
            color: #fff;
            font-size: 1rem;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <div class="logo" onclick="goHome()">Actvi.</div>
            <div class="img">
                <img src="/images/{{ request.user.profileImage }}" onclick="goProfile()" onmouseover="showLogout()">
            </div>
        </nav>
    </header>

    <div id="logout-butt" onmouseleave="hideLogout()">
        <a href="{% url 'activity:logout' %}">Logout</a>
    </div>

    {% block content %}
    {% endblock %}
    <script>
    const goHome = () => {
        window.location.href = "{% url 'activity:home' %}";
    }

    const goProfile = () => {
        window.location.href = "{% url 'activity:profile-host' %}";
    }

    const showLogout = () => {
        document.getElementById("logout-butt").style.display = "block";
    }

    const hideLogout = () => {
        document.getElementById("logout-butt").style.display = "none";
    }

    const toEditPro = () => {
        window.location.href = "{% url 'activity:updateuser' request.user.id %}";
    }


    
    </script>
</body>
</html>

activity/templates/activity/login.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="{% static 'activity/css/login.css' %}">
</head>
<body>
    <main>

        <div class="form-container">
            <div class="form-section">
                <div class="profile">
                    <div class="form-name"> 
                        
                        {% for m in messages %}       
                            <div class="message">
                                <p>{{ m }}</p>
                            </div>
                        {% empty %}
                        {% endfor %}
                        <h1>Actvi.</h1>
                        <p>@Singin</p>
                    </div>
                </div>
                <div class="main-form">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="text">
                            <input id="username" type="text" placeholder="Username" name="username">
                        </div>
                        <div class="text">
                            <input id="username" type="password" placeholder="Password" name="password">
                        </div>

                        <input type="submit" id="form-submit" value="Sign In">
                        <p style="text-align: center;">Did not have an account yet: <a href="{% url 'activity:register' %}">Signup</a></p>
                    </form>
                </div>
            </div>
            
            <!-- <div class="cover">
                <h1>Actvi.</h1>
                <p>Create an account with us and join many activity.</p>
            </div> -->
        </div>
    </main>
</body>
</html>
<!-- <form method="post">
    {% csrf_token %}
    <label for="username">username</label>
    <input type="text" name="username" id="username">

    <label for="password">password</label>
    <input type="password" name="password" id="password">

    {% for m in messages %}
        <p>{{ m }}</p>
    {% endfor %}

    <input type="submit" value="Login">
</form> -->

activity/templates/activity/profile-host.html
{% include "activity/base.html" %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'activity/css/user.css' %}">
</head>
<main>
    <div class="profile-section">
        <div class="profile-container" onclick="toEditPro()" style="cursor: pointer;">
            <div class="profile-edit">
                <img src="{% static 'activity/img/edit.png' %}" alt="" >
            </div>
            <div class="profile-picture">
                <img src="/images/{{ request.user.profileImage }}" alt="">
            </div>

        </div>

        <div class="user-info">
            <div class="name">
                <h1>{{ request.user.first_name | title }} {{ request.user.last_name | title }}</h1>
                <p>@{{ request.user.username }}</p>
            </div>
            <div class="activity-info-user">
                <p class="host"> 
                    <span class="number">
                    {% if  hostCount > 9%}
                        {{ hostCount }}                    
                    {% elif hostCount == 0%}
                        0
                    {% else %}
                        0{{ hostCount }}
                    {%endif%}
                    </span> Host
                </p>

                <p class="join">
                    <span class="number">
                    {% if  joinCount > 9%}
                        {{ joinCount }}
                    {% elif joinCount == 0%}
                        0
                    {% else %}
                        0{{ joinCount }}
                    {%endif%}
                    </span> Join
                </p>
            </div>
            <p class="bio">"{{ request.user.userBio }}"</p>
        </div>
    </div>



    <div class="switcher">
        <div class="create-activity">
            <a href="{% url 'activity:create' %}">Create Activity</a>
        </div>
        <div class="switcher-button">
            <div class="butt-user active" onclick="goYouHost()">Activity you host</div>
            <div class="butt-user" onclick="goYouJoin()">Activity you join</div>
        </div>
        
    </div>

    <!-- ACTIVITY YOU HOST -->
    <div class="activities">
        {% if activities %}

        {% for activity in activities %}

        <div class="activity-card">
            <div class="profile">
                <div class="card-profile">
                    <div class="profile-image">
                        <img src="/images/{{ activity.activity.activityOrganizer.profileImage }}" alt="">
                    </div>
                    <div class="name">
                        <div class="fullname">{{ activity.activity.activityOrganizer.first_name | title }} {{ activity.activity.activityOrganizer.last_name | title }}</div>
                        <div class="username">@{{ activity.activity.activityOrganizer }}</div>
                    </div>
                </div>
                <div class="time">{{ activity.activity.activityOpenDate | date:'d M Y' }}</div>
            </div>

            <div class="activity-info">
                <div class="activity-detail">
                    <p>{{ activity.activity.activityDate | date:'d F Y'}}</p>
                    <p>{{ activity.activity.activityLocation }}</p>
                    <h1>{{ activity.activity.activityTitle }}</h1>
                    <p class="list">Particepance's List</p>
                    <div class="par-list">
                            {% for p in activity.particepance %}
                            <!-- <h1>{{ p }}</h1> -->
                                <div class="pro">
                                    <img src="/images/{{ p.userID.profileImage }}" alt="">
                                </div>
                            {% endfor %}
                        
                            {% if activity.lastestParticepance > 5  %}
                                <p class="extra">+{{ activity.lastestParticepance|add:"-5" }}</p>
                            {% endif %}
                        
                    </div>
                </div>
                <div class="activity-action">
                    
                    <div class="butt detail-button">
                        <a href="{% url 'activity:more-info' activity.activity.id %}">More Information</a>
                    </div>
                    
                    <div class="butt detail-button">
                        <a href="{% url 'activity:update' activity.activity.id %}">Edit Activity</a>
                    </div>
                    <div class="butt join-button">
                        <form id="join-form">
                            <a href="{% url 'activity:delete' activity.activity.id %}">Delete Activity</a>
                        </form>
                        <!-- <a href="#">Join now</a> -->
                    </div>

                </div>
            </div>
        </div>
        {% endfor %}        
        {% else %}

        <p style="text-align: center; margin-top: 10rem;">You haven't host any activity yet</p>

        {% endif %}

    </div>

<script>
    const goYouHost = () => {
        window.location.href = "{% url 'activity:profile-host' %}";
    }

    const goYouJoin = () => {
        window.location.href = "{% url 'activity:profile-join' %}";
    }
</script>
</main>

{% endblock %}

activity/templates/activity/profile-join.html
{% include "activity/base.html" %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'activity/css/user.css' %}">
</head>
<main>
    <div class="profile-section">
        <div class="profile-container" onclick="toEditPro()" style="cursor: pointer;">
            <div class="profile-edit">
                <img src="{% static 'activity/img/edit.png' %}" alt="">
            </div>
            <div class="profile-picture">
                <img src="/images/{{ request.user.profileImage }}" alt="">
            </div>

        </div>

        <div class="user-info">
            <div class="name">
                <h1>{{ request.user.first_name | title }} {{ request.user.last_name | title }}</h1>
                <p>@{{ request.user.username }}</p>
            </div>
            <div class="activity-info-user">
                <p class="host"> 
                    <span class="number">
                    {% if  hostCount > 9%}
                        {{ hostCount }}                    
                    {% elif hostCount == 0%}
                        0
                    {% else %}
                        0{{ hostCount }}
                    {%endif%}
                    </span> Host
                </p>

                <p class="join">
                    <span class="number">
                    {% if  joinCount > 9%}
                        {{ joinCount }}
                    {% elif joinCount == 0%}
                        0
                    {% else %}
                        0{{ joinCount }}
                    {%endif%}
                    </span> Join
                </p>
            </div>
            <p class="bio">"{{ request.user.userBio }}"</p>
        </div>
    </div>



    <div class="switcher">
        <div class="create-activity">
            <a href="{% url 'activity:create' %}">Create Activity</a>
        </div>
        <div class="switcher-button">
            <div class="butt-user" onclick="goYouHost()">Activity you host</div>
            <div class="butt-user active" onclick="goYouJoin()">Activity you join</div>
        </div>
        
    </div>

    <!-- ACTIVITY YOU HOST -->
    <div class="activities">
        {% for activity in activities %}

        <div class="activity-card">
            <div class="profile">
                <div class="card-profile">
                    <div class="profile-image">
                        <img src="/images/{{ activity.activity.activityOrganizer.profileImage }}" alt="">
                    </div>
                    <div class="name">
                        <div class="fullname">{{ activity.activity.activityOrganizer.first_name | title }} {{ activity.activity.activityOrganizer.last_name | title }}</div>
                        <div class="username">@{{ activity.activity.activityOrganizer }}</div>
                    </div>
                </div>
                <div class="time">{{ activity.activity.activityOpenDate | date:'d M Y' }}</div>
            </div>

            <div class="activity-info">
                <div class="activity-detail">
                    <p>{{ activity.activity.activityDate | date:'d F Y'}}</p>
                    <p>{{ activity.activity.activityLocation }}</p>
                    <h1>{{ activity.activity.activityTitle }}</h1>
                    <p class="list">Particepance's List</p>
                    <div class="par-list">
                            {% for p in activity.particepance %}
                            <!-- <h1>{{ p }}</h1> -->
                                <div class="pro">
                                    <img src="/images/{{ p.userID.profileImage }}" alt="">
                                </div>
                            {% endfor %}
                        
                            {% if activity.lastestParticepance > 5  %}
                                <p class="extra">+{{ activity.lastestParticepance|add:"-5" }}</p>
                            {% endif %}
                        
                    </div>
                </div>
                <div class="activity-action">
                    <div class="activity-status">
                        <div class="dot"></div>
                        <p>Open until {{ activity.activity.activityCloseDate | date:'d M Y' }}</p>
                    </div>
                    <p class="notice">please join the event before the closing date.</p>
                    
                    <div class="butt leave-button">
                        <form id="join-form">
                            {% csrf_token %}
                            <input type="hidden" id="userID" name="userID" value="{{ request.user.id }}">
                            <input type="hidden" id="activityID" name="activityID" value="{{ activity.id }}">
                            <input id="leave-butt" type="submit" value="Leave" data-tosend="{{ activity.activity.id }}">
                        </form>
                    </div>

                    <div class="butt detail-button">
                        <a href="{% url 'activity:more-info' activity.activity.id %}">More Information</a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <p style="text-align: center; margin-top: 10rem;">You haven't join any activity yet (boring...)</p>
        {% endfor %}
    </div>

<script>
    const goYouHost = () => {
        window.location.href = "{% url 'activity:profile-host' %}";
    }

    const goYouJoin = () => {
        window.location.href = "{% url 'activity:profile-join' %}";
    }

    $(document).on('click', '#leave-butt', function(e) {
        e.preventDefault();
        console.log(e.target.dataset.tosend)
        $.ajax({
            type: 'POST',
            // url: `/deleteActivity/${$('#userID').val()}/${e.target.dataset.tosend}`,
            url: "{% url 'activity:leave' %}",
            data: {
                userID: $('#userID').val(),
                activityID: e.target.dataset.tosend,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(data) {
                console.log(data)
                // console.log("DONE!")
                // console.log(data)
                // $("#join-form")[0].reset();
                location.reload();
            }
        })
        $("#leave-form")[0].reset();
    })
</script>
</main>

{% endblock %}